### ISSUE TITLE
Should support null body

### ISSUE THREAD

**Issue by bikegriffith** [coub/raml_ruby#13]
Using this simple document:

```
#%RAML 0.8
title: example
baseUri: http://example.com
/name:
  get:
    responses:
      200:
        body:
          text/plain: !!null
```

... it raises an error `body property must be a map with map values: {"text/plain"=>"text/plain"}`

The RAML 0.8 spec allows this <https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#body>

**Comment by xhh** [comment]
```

**Comment by xhh** [comment]
I have a similar issue. With the following spec:

```yaml
#%RAML 0.8
title: example
baseUri: http://example.com
/name:
  get:
    responses:
      200:
```

I got this error: `Raml::InvalidProperty: responses property must be a map with map values: {200=>200}`.
One thing is that `{200 => nil}` becomes `{200 => 200}`, after the [`expand_includes`](https://github.com/coub/raml_ruby/blob/master/lib%2Framl%2Fparser.rb#L22) method is called, just like `{"text/plain"=>"text/plain"}` in the description of this issue. Is it expected?
Also, `{200 => nil}` is valid for response when validating with [raml-cop](https://github.com/thebinarypenguin/raml-cop), but the hash validation does not allow nil.
