### ISSUE TITLE
Make eliasenvy main repo

### ISSUE THREAD

**Issue by polmiro** [coub/raml_ruby#4]
https://github.com/eliaslevy/raml_ruby

Can we make @eliaslevy the main repository? The implementation is close to be completed there. Still some little parts missing. I want to contribute with this project but I don't think there's seems to be much of a maintenance.

If you were interested I would be happy to take over the maintenance and continue contributing with the missing parts.

Pol

**Comment by eliaslevy** [comment]
@coub merged my branch in #3 .
