### ISSUE TITLE
Releasing version to Rubygems

### ISSUE THREAD

**Issue by polmiro** [coub/raml_ruby#8]
Hi kgorin!

Could we release a current version of the repository? I have a few gems that I would like to release but I can't use ```gem 'raml_ruby', :github => 'coub/raml_ruby'``` or anything similar in the gemspec.

Thanks!

Pol

**Comment by kgorin** [comment]
Hi @polmiro 

It is now published at https://rubygems.org/gems/raml_ruby

Thanks for reporting this!

**Comment by bikegriffith** [comment]
Great to see this, you probably should update the README to reflect new way to use.  Thanks!
